@startuml
left to right direction
actor "Administrateur" as Admin
actor "Manager Energie" as Manager
actor "Consultant" as Consultant

rectangle "Eco-Optimize BI" {
  
  usecase "S'authentifier" as UC1
  usecase "Consulter tableau de bord KPI" as UC2
  usecase "Gérer les utilisateurs" as UC3
  usecase "Saisir relevé conso" as UC4
  usecase "Configurer alertes" as UC5
  usecase "Comparer benchmarks" as UC6
  
  Admin --> UC1
  Admin --> UC3
  
  Manager --> UC1
  Manager --> UC2
  Manager --> UC4
  Manager --> UC5
  
  Consultant --> UC1
  Consultant --> UC2
  Consultant --> UC6
  
  UC2 ..> UC4 : <<include>>
  UC5 ..> UC2 : <<extend>>
}
@enduml
